name: QA

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Full image name'
        required: true
        default: 'docker.kurrent.io/kurrent-staging/kurrentdb:ci'
        type: string

jobs:
  test:
    name: Test
    uses: ./.github/workflows/tests.yml
    with:
      image: ${{ inputs.image }}
